project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('quiz.urls', namespace='quiz'))
]

quiz/urls.py
from django.apps import apps
from django.urls import path

from .views import (
    QuizListView,
    QuizDetailView,
    QuizCreateView,
    QuizUpdateView,
    QuizDeleteView,
    QuizStartView,
    QuestionCreateView,
    QuestionDeleteView,
    QuestionUpdateView
)

app_name = apps.get_app_config('quiz').name

urlpatterns = [
    path('', QuizListView.as_view(), name='list'),
    path('quiz/<slug:slug>/detail/', QuizDetailView.as_view(), name='detail'),
    path('quiz/create/new/', QuizCreateView.as_view(), name='create'),
    path('quiz/<slug:slug>/update/', QuizUpdateView.as_view(), name='update'),
    path('quiz/<slug:slug>/delete/', QuizDeleteView.as_view(), name='delete'),
    path('quiz/<slug:slug>/start/', QuizStartView.as_view(), name='start'),
    path(
        'quiz/<slug:slug>/question/create/',
        QuestionCreateView.as_view(),
        name='question_create'
    ),
    path(
        'quiz/question/<int:pk>/update/',
        QuestionUpdateView.as_view(),
        name='question_update'
    ),
    path(
        'quiz/question/<int:pk>/delete/',
        QuestionDeleteView.as_view(),
        name='question_delete'
    )
]

quiz/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class Quiz(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(null=False, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('quiz:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Quiz'
        verbose_name_plural = 'Quizzes'


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=500)

    def __str__(self):
        return self.question


class Answer(models.Model):
    answer = models.CharField(max_length=300)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

quiz/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import (
    Answer,
    Question
)


class QuizForm(forms.Form):
    def __init__(self, quiz, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.quiz = quiz
        for question in self.quiz.question_set.all():
            field_name = "question_%d" % question.pk
            choices = []
            for answer in question.answer_set.all():
                choices.append((answer.pk, answer.answer,))
            self.fields[field_name] = forms.ChoiceField(
                label=question.question,
                required=True, choices=choices,
                widget=forms.RadioSelect
            )


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('answer', 'is_correct')


AnswerInlineFormset = inlineformset_factory(
    Question,
    Answer,
    form=AnswerForm,
    extra=5,
    max_num=5
)

quiz/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.http import Http404
from django.shortcuts import (
    redirect,
    render
)
from django.urls import (
    reverse,
    reverse_lazy
)
from django.views.generic import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    DeleteView,
    FormMixin,
    UpdateView
)
from django.views.generic.list import ListView

from .forms import (
    AnswerInlineFormset,
    QuestionForm,
    QuizForm
)
from .models import (
    Answer,
    Question,
    Quiz
)


class AuthRequiredMixin(LoginRequiredMixin):
    login_url = '/accounts/login/'
    redirect_field_name = '/'


class StaffRequiredMixin(AuthRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class SuperUserRequiredMixin(AuthRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class QuizListView(AuthRequiredMixin, ListView):
    model = Quiz


class QuizDetailView(AuthRequiredMixin, DetailView):
    model = Quiz


class QuizCreateView(SuperUserRequiredMixin, CreateView):
    model = Quiz
    fields = ('name', 'description')


class QuizUpdateView(SuperUserRequiredMixin, UpdateView):
    model = Quiz
    fields = ('name', 'description')


class QuizDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Quiz
    success_url = reverse_lazy('quiz:list')


class QuizStartView(StaffRequiredMixin, FormMixin, DetailView):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_start.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'quiz': self.get_object(),
        })
        return kwargs

    def post(self, request, *args, **kwargs):
        form = QuizForm(quiz=self.get_object(), data=request.POST)
        if form.is_valid():
            max_score = 0
            score = 0
            for answer_pk in form.cleaned_data.values():
                answer = Answer.objects.get(pk=answer_pk)
                max_score += 1
                if answer.is_correct:
                    score += 1
            return render(
                request,
                'quiz/results.html',
                {'max_score': max_score, 'score': score, 'quiz': form.quiz}
            )


class QuestionCreateView(SuperUserRequiredMixin, CreateView):
    form_class = QuestionForm
    model = Question

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        answer_form = AnswerInlineFormset()

        return self.render_to_response(
            self.get_context_data(form=form, answer_form=answer_form)
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        answer_form = AnswerInlineFormset(self.request.POST)

        if form.is_valid() and answer_form.is_valid():
            return self.form_valid(form, answer_form)
        return self.form_invalid(form, answer_form)

    def form_valid(self, form, answer_form):
        quiz = Quiz.objects.get(slug=self.kwargs['slug'])
        self.object = form.save(commit=False)
        self.object.quiz = quiz
        self.object.save()

        answer_form.instance = self.object
        answer_form.save()
        return redirect(reverse('quiz:detail', kwargs={'slug': quiz.slug}))

    def form_invalid(self, form, answer_form):
        return self.render_to_response(
            self.get_context_data(form=form, answer_form=answer_form)
        )

    def get_context_data(self, **kwargs):
        context = super(QuestionCreateView, self).get_context_data(**kwargs)

        try:
            context['quiz'] = Quiz.objects.get(slug=self.kwargs['slug'])
        except Quiz.DoesNotExist:
            raise Http404('Quiz does not exist.')

        if self.request.POST:
            context['form'] = QuestionForm(self.request.POST)
            context['answer_form'] = AnswerInlineFormset(self.request.POST)
        else:
            context['form'] = QuestionForm()
            context['answer_form'] = AnswerInlineFormset()

        return context


class QuestionDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Question

    def get_success_url(self):
        quiz_slug = self.object.quiz.slug
        return reverse('quiz:detail', kwargs={'slug': quiz_slug})


class QuestionUpdateView(SuperUserRequiredMixin, UpdateView):
    form_class = QuestionForm
    model = Question

    def get_success_url(self):
        quiz_slug = self.object.quiz.slug
        return reverse('quiz:detail', kwargs={'slug': quiz_slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        answer_form = AnswerInlineFormset(
            self.request.POST,
            instance=self.object
        )

        if form.is_valid() and answer_form.is_valid():
            return self.form_valid(form, answer_form)
        return self.form_invalid(form, answer_form)

    def form_valid(self, form, answer_form):
        self.object = form.save(commit=False)
        self.object.save()

        answer_form.instance = self.object
        answer_form.save()
        return redirect(self.get_success_url())

    def form_invalid(self, form, answer_form):
        return self.render_to_response(
            self.get_context_data(form=form, answer_form=answer_form)
        )

    def get_context_data(self, **kwargs):
        context = super(QuestionUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = QuestionForm(
                self.request.POST,
                instance=self.object
            )
            context['answer_form'] = AnswerInlineFormset(
                self.request.POST,
                instance=self.object
            )
        else:
            context['form'] = QuestionForm(instance=self.get_object())
            context['answer_form'] = AnswerInlineFormset(
                instance=self.get_object()
            )

        return context

templates/quiz/question_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container text-center">
    <form method="post">
        {% csrf_token %}
        <h3>Warning!</h3>
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Yes">
        <a href="{% url 'quiz:list' %}" class="btn btn-primary">No</a>
    </form>
</div>
{% endblock content %}

templates/quiz/question_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <form method="post">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                {% if quiz %}
                    <h4>{{ quiz.name }} - Add question</h4>
                {% endif %}
                {% if object %}
                    <h4>{{ object.question }} - Edit question</h4>
                {% endif %}
            </div>
            <div class="card-body">
                {{ form.non_form_errors }}
                {{ form|crispy }}
                <h5 class="text-info">Add Answers</h5>
                {{ answer_form.non_form_errors }}
                {{ answer_form.management_form }}
                {% for form in answer_form %}
                    <span class="badge badge-pill badge-primary">{{ forloop.counter }}</span>
                    {{ form|crispy }}
                {% endfor %}
            </div>
        </div>
        <div class="mt-3 mb-5">
            <button type="submit" class="px-5 btn btn-info">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

templates/quiz/quiz_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container text-center">
    <form method="post">
        {% csrf_token %}
        <h3>Warning!</h3>
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Yes">
        <a href="{% url 'quiz:list' %}" class="btn btn-primary">No</a>
    </form>
</div>
{% endblock content %}

templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section>
  <div class="container">
    <h3>{{ quiz.name }}</h3>
    <p>{{ quiz.description }}</p>
    <p>
      {% if request.user.is_superuser %}
        <a href="{% url 'quiz:question_create' quiz.slug %}" class="btn btn-sm btn-success"><i class="fa-solid fa-plus mr-2"></i>Add Question</a>
      {% endif %}
    </p>
    <div class="row">
      {% for question in quiz.question_set.all %}
        <div class="col-md-4 mb-3">
          <div class="card h-100">
            <div class="card-header">
              <h4><span class="badge badge-primary">Question {{ forloop.counter }}</span></h4>
            </div>
            <div class="card-body">
              <h6>{{ question.question }}</h6>
              {% if request.user.is_staff %}
                <ol>
                  {% for answer in question.answer_set.all %}
                    <li>{{ answer.answer }}</li>
                  {% endfor %}
                </ol>
              {% endif %}
            </div>
            {% if request.user.is_superuser %}
              <div class="card-footer text-center">
                <a href="{% url 'quiz:question_update' question.pk %}" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square mr-2"></i>Edit</a>
                <a href="{% url 'quiz:question_delete' question.pk %}" class="btn btn-sm btn-danger"><i class="fa-solid fa-trash mr-2"></i>Delete</a>
              </div>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

templates/quiz/quiz_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    {% if object %}
        <h3>{{ object.name }} - Edit</h3>
    {% else %}
        <h3>New quiz</h3>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="{% if object %}Rename{% else %}Create{% endif %}">
    </form>
</div>
{% endblock content %}

templates/quiz/quiz_list.html
{% extends 'base.html' %}

{% block content %}
<section>
  <div class="container">
    <h1 class="mb-3">All Quizzes/Tests</h1>
    <div class="row mb-3">
      {% for quiz in quiz_list %}
        <div class="col-lg-4 mb-3">
          <div class="card text-center h-100">
            <h5 class="card-header">{{ quiz.name }}</h5>
            <div class="card-body">
              <p class="card-text">{{ quiz.description }}</p>
            </div>
            <div class="card-footer">
              {% if request.user.is_staff %}
                <a href="{% url 'quiz:start' quiz.slug %}" class="btn btn-sm btn-primary"><i class="fa-solid fa-play mr-2"></i>Start Quiz</a>
              {% endif %}
              {% if request.user.is_authenticated %}
                <a href="{% url 'quiz:detail' quiz.slug %}" class="btn btn-sm btn-primary"><i class="fa-solid fa-eye mr-2"></i></i>View Questions</a>
              {% endif %}
              {% if request.user.is_superuser %}
                <hr>
                <a href="{% url 'quiz:update' quiz.slug %}" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square mr-2"></i>Rename</a>
                <a href="{% url 'quiz:delete' quiz.slug %}" class="btn btn-sm btn-danger"><i class="fa-solid fa-trash mr-2"></i>Delete</a>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

templates/quiz/quiz_start.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section>
  <div class="container">
    <h3>{{ quiz.name }}</h3>
    <p>{{ quiz.description }}</p>
    <hr>
    <form method="post">
      {% csrf_token %}
      {# form|crispy #}
      <div class="row">
        {% for field in form %}
          <div class="col-md-4 mb-3">
            <div class="card h-100">
              <div class="card-header">Question {{ forloop.counter }}</div>
              <div class="card-body">
                <div class="fieldWrapper">
                  {{ field.errors }}
                  {{ field|as_crispy_field }}
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <input class="btn btn-primary mt-3 mb-5" type="submit" value="Submit">
    </form>

  </div>
</section>
{% endblock content %}

templates/quiz/results.html
{% extends 'base.html' %} {% block content %}
<div class="container text-center">
  <div class="card">
    <h5 class="card-header">{{ quiz.name }} - Your Score</h5>
    <div class="card-body">
      <p>
        Total number of questions -
        <span class="badge badge-primary">{{ max_score }}</span>.
      </p>
      <p>
        Answered correctly -
        <span class="badge badge-primary">{{ score }}</span>.
      </p>
      <a href="{% url 'quiz:list' %}" class="btn btn-primary"
        >Return to Quiz List</a
      >
    </div>
  </div>
</div>
{% endblock content %}