project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('quiz.urls', namespace='quiz'))
]

quiz/urls.py
from django.apps import apps
from django.urls import path

from .views import (
    QuizListView,
    QuizDetailView,
    QuizCreateView,
    QuizUpdateView,
    QuizDeleteView,
    QuizStartView,
    QuestionCreateView,
    QuestionDeleteView,
    QuestionUpdateView
)

app_name = apps.get_app_config('quiz').name

urlpatterns = [
    path('', QuizListView.as_view(), name='list'),
    path('quiz/<slug:slug>/detail/', QuizDetailView.as_view(), name='detail'),
    path('quiz/create/new/', QuizCreateView.as_view(), name='create'),
    path('quiz/<slug:slug>/update/', QuizUpdateView.as_view(), name='update'),
    path('quiz/<slug:slug>/delete/', QuizDeleteView.as_view(), name='delete'),
    path('quiz/<slug:slug>/start/', QuizStartView.as_view(), name='start'),
    path(
        'quiz/<slug:slug>/question/create/',
        QuestionCreateView.as_view(),
        name='question_create'
    ),
    path(
        'quiz/question/<int:pk>/update/',
        QuestionUpdateView.as_view(),
        name='question_update'
    ),
    path(
        'quiz/question/<int:pk>/delete/',
        QuestionDeleteView.as_view(),
        name='question_delete'
    )
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Quiz Manager</title>
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
  {% block scripts %}
  {% endblock scripts %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <a class="navbar-brand" href="{% url 'quiz:list' %}"><i class="fa-solid fa-spell-check mr-2"></i>Quiz Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        {% url 'quiz:list' as url %}
        <li class="nav-item {% if request.path == url %}active{% endif %}"><a class="nav-link" href="{{ url }}"><i class="fa-solid fa-align-left mr-2"></i>Quiz List</a></li>
        {% if request.user.is_superuser %}
          {% url 'quiz:create' as url %}
          <li class="nav-item {% if request.path == url %}active{% endif %}"><a class="nav-link" href="{{ url }}"><i class="fa-solid fa-plus mr-2"></i></i>Create a new quiz</a></li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Logged as: <b>{{ request.user }}</b>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if request.user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
            {% if request.user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'login' %}">Log in</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <footer class="page-footer font-small bg-light fixed-bottom">
    <div class="footer-copyright text-center py-1 text-muted">© 2022 Copyright: Danila Veselov | Exeter College</div>
  </footer>
<script src="{% static "js/jquery-3.2.1.slim.min.js" %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="{% static "js/popper.min.js" %}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static "js/bootstrap.min.js" %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>